# Generated by Django 5.1.4 on 2025-01-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_doctor_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.userprofile', verbose_name='doctor'),
        ),
    ]
