# Generated by Django 5.1.4 on 2025-01-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_doctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='data.userprofile'),
        ),
    ]
