# Generated by Django 5.1.4 on 2025-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_doctor_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
